### ISSUE TITLE
What is the wiring for the ESP32 ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [kthnxbai/FindMyArduino#2]
Hello !

I would like to know how to wire the ESP32 to the GPS Module.

Thank you !

**Comment by tamerciaga** [comment]
Please take a look here: https://randomnerdtutorials.com/guide-to-neo-6m-gps-module-with-arduino/
You must define the two pins in your code.

**Comment by GeorgeFlorian** [comment]
> Please take a look here: https://randomnerdtutorials.com/guide-to-neo-6m-gps-module-with-arduino/
> You must define the two pins in your code.

What if I can't use RX2 and TX2  ? On my board those pins aren't connected.
And I can't use TX and RX either because those pins are internally linked to something else.
What can I do ?
